-- AI Chat Conversations Table
create table if not exists ai_conversations (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid references workspaces(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,

  -- Conversation metadata
  title text, -- Auto-generated by AI, can be null initially
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  last_message_at timestamptz default now(),

  -- Message count and usage
  message_count int default 0,
  total_tokens_used int default 0,
  total_cost decimal(10, 6) default 0
);

-- AI Chat Messages Table
create table if not exists ai_messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid references ai_conversations(id) on delete cascade not null,

  -- Message content
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,

  -- Reasoning tokens (for deepseek-r1 and similar models)
  reasoning text, -- The thinking/reasoning process
  reasoning_details jsonb, -- Structured reasoning details from API

  -- Token usage tracking
  input_tokens int default 0,
  output_tokens int default 0,
  reasoning_tokens int default 0,
  total_tokens int default 0,
  cost decimal(10, 6) default 0,

  -- Model used
  model text default 'deepseek/deepseek-r1',

  -- Timestamps
  created_at timestamptz default now(),

  -- Order in conversation
  sequence_number int not null
);

-- AI File Attachments Table
create table if not exists ai_file_attachments (
  id uuid primary key default gen_random_uuid(),
  message_id uuid references ai_messages(id) on delete cascade not null,

  -- File metadata
  file_name text not null,
  file_type text not null, -- 'pdf', 'excel', 'word', 'image'
  file_size int not null, -- in bytes
  mime_type text not null,

  -- Storage
  storage_path text not null, -- Path in Supabase storage
  storage_url text, -- Public or signed URL

  -- Extracted content (for processing)
  extracted_text text, -- For PDFs, Word docs
  extracted_data jsonb, -- For Excel, structured data
  preview_url text, -- For images, preview thumbnails

  -- Processing status
  processing_status text default 'pending' check (processing_status in ('pending', 'processing', 'completed', 'failed')),
  extraction_model text, -- Model used for extraction (e.g., 'qwen/qwen-2.5-vl-32b-instruct')

  created_at timestamptz default now()
);

-- AI Usage Tracking Table (per user per month)
create table if not exists ai_usage_tracking (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  workspace_id uuid references workspaces(id) on delete cascade not null,

  -- Time period (format: YYYY-MM)
  month text not null, -- e.g., '2025-01'

  -- Usage metrics
  total_messages int default 0,
  total_tokens int default 0,
  total_cost decimal(10, 4) default 0,

  -- File processing usage
  files_processed int default 0,

  -- Limits (soft limits)
  message_limit int default 1000, -- Soft limit per month
  token_limit int default 1000000, -- Soft limit per month

  -- Warning flags
  warning_shown boolean default false,

  created_at timestamptz default now(),
  updated_at timestamptz default now(),

  -- Unique constraint per user per month
  unique(user_id, workspace_id, month)
);

-- Indexes for performance
create index if not exists idx_ai_conversations_workspace on ai_conversations(workspace_id);
create index if not exists idx_ai_conversations_user on ai_conversations(user_id);
create index if not exists idx_ai_conversations_updated on ai_conversations(last_message_at desc);

create index if not exists idx_ai_messages_conversation on ai_messages(conversation_id, sequence_number);
create index if not exists idx_ai_messages_created on ai_messages(created_at);

create index if not exists idx_ai_files_message on ai_file_attachments(message_id);
create index if not exists idx_ai_files_status on ai_file_attachments(processing_status);

create index if not exists idx_ai_usage_user_month on ai_usage_tracking(user_id, month);
create index if not exists idx_ai_usage_workspace on ai_usage_tracking(workspace_id, month);

-- Enable RLS
alter table ai_conversations enable row level security;
alter table ai_messages enable row level security;
alter table ai_file_attachments enable row level security;
alter table ai_usage_tracking enable row level security;

-- RLS Policies for ai_conversations
create policy "Users can view their own conversations"
  on ai_conversations for select
  using (user_id = auth.uid());

create policy "Users can insert their own conversations"
  on ai_conversations for insert
  with check (user_id = auth.uid());

create policy "Users can update their own conversations"
  on ai_conversations for update
  using (user_id = auth.uid());

create policy "Users can delete their own conversations"
  on ai_conversations for delete
  using (user_id = auth.uid());

-- RLS Policies for ai_messages
create policy "Users can view messages in their conversations"
  on ai_messages for select
  using (
    conversation_id in (
      select id from ai_conversations where user_id = auth.uid()
    )
  );

create policy "Users can insert messages in their conversations"
  on ai_messages for insert
  with check (
    conversation_id in (
      select id from ai_conversations where user_id = auth.uid()
    )
  );

create policy "Users can update messages in their conversations"
  on ai_messages for update
  using (
    conversation_id in (
      select id from ai_conversations where user_id = auth.uid()
    )
  );

create policy "Users can delete messages in their conversations"
  on ai_messages for delete
  using (
    conversation_id in (
      select id from ai_conversations where user_id = auth.uid()
    )
  );

-- RLS Policies for ai_file_attachments
create policy "Users can view file attachments in their messages"
  on ai_file_attachments for select
  using (
    message_id in (
      select m.id from ai_messages m
      join ai_conversations c on m.conversation_id = c.id
      where c.user_id = auth.uid()
    )
  );

create policy "Users can insert file attachments in their messages"
  on ai_file_attachments for insert
  with check (
    message_id in (
      select m.id from ai_messages m
      join ai_conversations c on m.conversation_id = c.id
      where c.user_id = auth.uid()
    )
  );

create policy "Users can update file attachments in their messages"
  on ai_file_attachments for update
  using (
    message_id in (
      select m.id from ai_messages m
      join ai_conversations c on m.conversation_id = c.id
      where c.user_id = auth.uid()
    )
  );

create policy "Users can delete file attachments in their messages"
  on ai_file_attachments for delete
  using (
    message_id in (
      select m.id from ai_messages m
      join ai_conversations c on m.conversation_id = c.id
      where c.user_id = auth.uid()
    )
  );

-- RLS Policies for ai_usage_tracking
create policy "Users can view their own usage"
  on ai_usage_tracking for select
  using (user_id = auth.uid());

create policy "Users can insert their own usage"
  on ai_usage_tracking for insert
  with check (user_id = auth.uid());

create policy "Users can update their own usage"
  on ai_usage_tracking for update
  using (user_id = auth.uid());

-- Function to update conversation updated_at and last_message_at
create or replace function update_ai_conversation_on_message()
returns trigger as $$
begin
  update ai_conversations
  set
    updated_at = now(),
    last_message_at = now(),
    message_count = message_count + 1,
    total_tokens_used = total_tokens_used + new.total_tokens,
    total_cost = total_cost + new.cost
  where id = new.conversation_id;

  return new;
end;
$$ language plpgsql;

-- Trigger for updating conversation on new message
create trigger update_ai_conversation_on_message_trigger
  after insert on ai_messages
  for each row
  execute function update_ai_conversation_on_message();

-- Function to update/create usage tracking
create or replace function track_ai_usage(
  p_user_id uuid,
  p_workspace_id uuid,
  p_tokens int,
  p_cost decimal
)
returns void as $$
declare
  v_month text;
begin
  v_month := to_char(now(), 'YYYY-MM');

  insert into ai_usage_tracking (user_id, workspace_id, month, total_messages, total_tokens, total_cost)
  values (p_user_id, p_workspace_id, v_month, 1, p_tokens, p_cost)
  on conflict (user_id, workspace_id, month)
  do update set
    total_messages = ai_usage_tracking.total_messages + 1,
    total_tokens = ai_usage_tracking.total_tokens + p_tokens,
    total_cost = ai_usage_tracking.total_cost + p_cost,
    updated_at = now();
end;
$$ language plpgsql;

-- Extend user_settings to include AI chat preferences
-- Add ai_chat_settings column to user_settings
do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_name = 'user_settings' and column_name = 'ai_chat_settings'
  ) then
    alter table user_settings add column ai_chat_settings jsonb default '{
      "show_reasoning": true,
      "auto_title": true,
      "monthly_message_limit": 1000,
      "file_upload_enabled": true
    }'::jsonb;
  end if;
end$$;

-- Create storage bucket for AI chat file attachments (to be run with Supabase CLI or dashboard)
-- This is a comment for manual setup:
-- insert into storage.buckets (id, name, public) values ('ai-chat-files', 'ai-chat-files', false);
--
-- create policy "Users can upload their AI chat files"
-- on storage.objects for insert
-- with check (bucket_id = 'ai-chat-files' and auth.uid()::text = (storage.foldername(name))[1]);
--
-- create policy "Users can view their AI chat files"
-- on storage.objects for select
-- using (bucket_id = 'ai-chat-files' and auth.uid()::text = (storage.foldername(name))[1]);
